[tool.poetry]
name = "python-poetry"
version = "1.7.0"
description = "A Python Docker image with Poetry installed and ready to use."
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.11.*"
click = "8.1.7"
python-on-whales = "0.65.0"

[tool.poetry.dev-dependencies]
pylint = "3.0.2"
pytest = "7.4.2"
pytest-cov = "4.1.0"
pytest-dotenv = "0.5.2"
coverage = "7.3.1"
black = "23.9.1"
pre-commit = "3.4.0"
semver = "3.0.1"
testcontainers = "3.7.1"
bcrypt = "4.0.1"
docker-image-py = "0.1.12"
furl = "2.1.3"

# https://docs.pytest.org/en/latest/reference/customize.html
[tool.pytest.ini_options]
testpaths = [
    "tests",
]

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 80
target-version = ["py311"]

[tool.pylint.main]
errors-only = true
recursive = "y"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
